#!/bin/bash

set -e

source ./helper.sh

# Parse command line arguments
PRESERVE_CONTAINERS=false
USE_PLAIN=false
NO_CACHE=false
FEATURE="common"
TEST_MODE="scenarios"                                    # 默认模式: scenarios, autogenerated, global
BASE_IMAGE="mcr.microsoft.com/devcontainers/base:ubuntu" # 用于 autogenerated 模式

usage() {
  echo "Usage: $0 [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -p, --preserve        不删除测试容器和镜像(执行后打印容器信息)"
  echo "  --plain               使用 plain 模式显示构建进度"
  echo "  --no-cache            删除所有 vsc- 开头的测试容器"
  echo "  -f, --feature NAME    指定要测试的 feature (默认: common)"
  echo "  -m, --mode MODE       测试模式: scenarios, autogenerated, global (默认: scenarios)"
  echo "  -i, --image IMAGE     基础镜像 (仅用于 autogenerated 模式)"
  echo "  -h, --help            显示此帮助信息"
  echo ""
  echo "测试模式说明:"
  echo "  scenarios      - 运行 scenarios 测试 (默认)"
  echo "  autogenerated  - 运行自动生成的测试，可指定基础镜像"
  echo "  global         - 运行全局场景测试"
  echo ""
  echo "示例:"
  echo "  $0                              # 运行 scenarios 测试"
  echo "  $0 -m autogenerated             # 运行自动生成的测试"
  echo "  $0 -m autogenerated -i debian:latest  # 针对 debian:latest 运行测试"
  echo "  $0 -m global                    # 运行全局场景测试"
  echo "  $0 --preserve                   # 执行后保留容器和镜像"
  echo "  $0 --plain                      # 使用 plain 模式显示详细输出"
  echo "  $0 --no-cache                   # 清理所有 vsc- 测试容器"
  echo "  $0 -f common -m scenarios       # 测试 common feature 的 scenarios"
  echo "  $0 --preserve --plain           # 保留容器并使用 plain 模式"

  exit 0
}

while [[ $# -gt 0 ]]; do
  case $1 in
  -p | --preserve)
    PRESERVE_CONTAINERS=true
    shift
    ;;
  --plain)
    USE_PLAIN=true
    shift
    ;;
  --no-cache)
    NO_CACHE=true
    shift
    ;;
  -f | --feature)
    FEATURE="$2"
    shift 2
    ;;
  -m | --mode)
    TEST_MODE="$2"
    if [[ "$TEST_MODE" != "scenarios" && "$TEST_MODE" != "autogenerated" && "$TEST_MODE" != "global" ]]; then
      echo "错误: 无效的测试模式 '$TEST_MODE'"
      echo "有效的模式: scenarios, autogenerated, global"
      echo ""
      usage
      exit 1
    fi
    shift 2
    ;;
  -i | --image)
    BASE_IMAGE="$2"
    shift 2
    ;;
  *)
    echo "未知选项: $1"
    echo ""
    usage
    exit 1
    ;;
  esac
done

[ "$help" = "true" ] && usage

# Handle no-cache mode
if [ "$NO_CACHE" = true ]; then
  echo "清理 vsc-*-features-uid 测试容器和构建缓存..."
  echo ""

  # 1. 删除容器
  VSC_CONTAINERS=$(docker ps -a --format "{{.ID}}\t{{.Image}}" | grep "vsc-.*-features-uid" | awk '{print $1}')
  if [ -n "$VSC_CONTAINERS" ]; then
    echo "找到以下容器:"
    docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.CreatedAt}}" | grep -E "CONTAINER ID|vsc-.*-features-uid"
    echo ""
    echo "正在删除容器..."
    echo "$VSC_CONTAINERS" | xargs docker rm -f
    echo "$(green '✓ 容器清理完成')"
  else
    echo "$(yellow '没有找到 vsc-*-features-uid 测试容器')"
  fi
  echo ""

  # 2. 删除镜像
  VSC_IMAGES=$(docker images --format "{{.ID}}\t{{.Repository}}" | grep "vsc-.*-features-uid" | awk '{print $1}')
  if [ -n "$VSC_IMAGES" ]; then
    echo "找到以下镜像:"
    docker images --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}\t{{.Size}}\t{{.CreatedAt}}" | grep -E "IMAGE ID|vsc-.*-features-uid"
    echo ""
    echo "正在删除镜像..."
    echo "$VSC_IMAGES" | xargs docker rmi -f
    echo "$(green '✓ 镜像清理完成')"
  else
    echo "$(yellow '没有找到 vsc-*-features-uid 测试镜像')"
  fi
  echo ""

  # 3. 清理构建缓存
  echo "正在清理 Docker 构建缓存..."
  docker builder prune -af
  echo "$(green '✓ 构建缓存清理完成')"
  echo ""

  echo "$(green '🎉 所有清理操作完成！')"
  exit 0
fi

# Set BUILDKIT_PROGRESS if plain mode is enabled
if [ "$USE_PLAIN" = true ]; then
  export BUILDKIT_PROGRESS=plain
  echo "使用 plain 模式显示构建进度"
fi

# Build the command based on test mode
case $TEST_MODE in
scenarios)
  echo "$(green '运行 scenarios 测试模式')"
  CMD="devcontainer features test -f $FEATURE --skip-autogenerated --skip-duplicated"
  ;;
autogenerated)
  echo "$(green '运行 autogenerated 测试模式')"
  CMD="devcontainer features test --skip-scenarios -f $FEATURE"
  if [ -n "$BASE_IMAGE" ]; then
    CMD="$CMD -i $BASE_IMAGE"
    echo "基础镜像: $BASE_IMAGE"
  else
    echo "$(yellow '提示: 可以使用 -i 选项指定基础镜像')"
  fi
  ;;
global)
  echo "$(green '运行 global 测试模式')"
  CMD="devcontainer features test --global-scenarios-only"
  if [ "$FEATURE" != "common" ]; then
    echo "$(yellow '注意: global 模式会忽略 -f/--feature 选项')"
  fi
  ;;
esac

# Add preserve flag if enabled
if [ "$PRESERVE_CONTAINERS" = true ]; then
  CMD="$CMD --preserve-test-containers"
  echo "将保留测试容器和镜像"
fi

CMD="$CMD $(pwd)"

echo "执行命令: $CMD"
echo ""

# Execute the command
eval $CMD

# Show container info if preserve mode is enabled
if [ "$PRESERVE_CONTAINERS" = true ]; then
  echo ""
  echo "=================================================="
  echo "保留的测试容器信息:"
  echo "=================================================="
  VSC_CONTAINERS=$(docker ps -a --format "{{.ID}}\t{{.Image}}" | grep "vsc-.*-features-uid" | awk '{print $1}')
  if [ -n "$VSC_CONTAINERS" ]; then
    docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.CreatedAt}}" | grep -E "CONTAINER ID|vsc-.*-features-uid"
    echo ""
    echo "$(green '提示: 使用 --no-cache 选项可以清理这些容器')"
  else
    echo "$(yellow '没有找到 vsc-*-features-uid 测试容器')"
  fi
  echo "=================================================="
fi
