#!/bin/bash

set -e

source ./helper.sh

# Parse command line arguments
PRESERVE_CONTAINERS=false
USE_PLAIN=false
NO_CACHE=false
FEATURE="common"

usage() {
  echo "Usage: $0 [OPTIONS]"
  echo ""
  echo "Options:"
  echo "  -p, --preserve        不删除测试容器和镜像(执行后打印容器信息)"
  echo "  --plain               使用 plain 模式显示构建进度"
  echo "  --no-cache            删除所有 vsc- 开头的测试容器"
  echo "  -f, --feature NAME    指定要测试的 feature (默认: common)"
  echo "  -h, --help            显示此帮助信息"
  echo ""
  echo "示例:"
  echo "  $0                    # 正常执行，测试 common feature"
  echo "  $0 --preserve         # 执行后保留容器和镜像，并打印容器信息"
  echo "  $0 --plain            # 使用 plain 模式显示详细输出"
  echo "  $0 --no-cache         # 清理所有 vsc- 测试容器"
  echo "  $0 -f hello           # 测试 hello feature"
  echo "  $0 --preserve --plain # 保留容器并使用 plain 模式"

  exit 0
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -p|--preserve)
      PRESERVE_CONTAINERS=true
      shift
      ;;
    --plain)
      USE_PLAIN=true
      shift
      ;;
    --no-cache)
      NO_CACHE=true
      shift
      ;;
    -f|--feature)
      FEATURE="$2"
      shift 2
      ;;
    *)
      echo "未知选项: $1"
      echo ""
      usage
      exit 1
      ;;
  esac
done

[ "$help" = "true" ] && usage

# Handle no-cache mode
if [ "$NO_CACHE" = true ]; then
  echo "清理 vsc-*-features-uid 测试容器和构建缓存..."
  echo ""
  
  # 1. 删除容器
  VSC_CONTAINERS=$(docker ps -a --format "{{.ID}}\t{{.Image}}" | grep "vsc-.*-features-uid" | awk '{print $1}')
  if [ -n "$VSC_CONTAINERS" ]; then
    echo "找到以下容器:"
    docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.CreatedAt}}" | grep -E "CONTAINER ID|vsc-.*-features-uid"
    echo ""
    echo "正在删除容器..."
    echo "$VSC_CONTAINERS" | xargs docker rm -f
    echo "$(green '✓ 容器清理完成')"
  else
    echo "$(yellow '没有找到 vsc-*-features-uid 测试容器')"
  fi
  echo ""
  
  # 2. 删除镜像
  VSC_IMAGES=$(docker images --format "{{.ID}}\t{{.Repository}}" | grep "vsc-.*-features-uid" | awk '{print $1}')
  if [ -n "$VSC_IMAGES" ]; then
    echo "找到以下镜像:"
    docker images --format "table {{.ID}}\t{{.Repository}}\t{{.Tag}}\t{{.Size}}\t{{.CreatedAt}}" | grep -E "IMAGE ID|vsc-.*-features-uid"
    echo ""
    echo "正在删除镜像..."
    echo "$VSC_IMAGES" | xargs docker rmi -f
    echo "$(green '✓ 镜像清理完成')"
  else
    echo "$(yellow '没有找到 vsc-*-features-uid 测试镜像')"
  fi
  echo ""
  
  # 3. 清理构建缓存
  echo "正在清理 Docker 构建缓存..."
  docker builder prune -af
  echo "$(green '✓ 构建缓存清理完成')"
  echo ""
  
  echo "$(green '🎉 所有清理操作完成！')"
  exit 0
fi

# Set BUILDKIT_PROGRESS if plain mode is enabled
if [ "$USE_PLAIN" = true ]; then
  export BUILDKIT_PROGRESS=plain
  echo "使用 plain 模式显示构建进度"
fi

# Build the command
CMD="devcontainer features test -f $FEATURE --skip-autogenerated --skip-duplicated"

# Add preserve flag if enabled
if [ "$PRESERVE_CONTAINERS" = true ]; then
  CMD="$CMD --preserve-test-containers"
  echo "将保留测试容器和镜像"
fi

CMD="$CMD $(pwd)"

echo "执行命令: $CMD"
echo ""

# Execute the command
eval $CMD

# Show container info if preserve mode is enabled
if [ "$PRESERVE_CONTAINERS" = true ]; then
  echo ""
  echo "=================================================="
  echo "保留的测试容器信息:"
  echo "=================================================="
  VSC_CONTAINERS=$(docker ps -a --format "{{.ID}}\t{{.Image}}" | grep "vsc-.*-features-uid" | awk '{print $1}')
  if [ -n "$VSC_CONTAINERS" ]; then
    docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.CreatedAt}}" | grep -E "CONTAINER ID|vsc-.*-features-uid"
    echo ""
    echo "$(green '提示: 使用 --no-cache 选项可以清理这些容器')"
  else
    echo "$(yellow '没有找到 vsc-*-features-uid 测试容器')"
  fi
  echo "=================================================="
fi
