#!/usr/bin/env -S node --import tsx
//MISE description="DevContainer Features 测试任务"
//USAGE flag "-t --test-type <type>" help="预设测试类型" {
//USAGE   choices "autogenerated" "global" "scenarios"
//USAGE }
//USAGE flag "-f --feature <feature>" help="预设 feature"
//USAGE flag "--workflow-matrix-images <images>" help="autogenerated 类型下按 workflow 矩阵多选基础镜像（逗号分隔）"
//USAGE flag "--scenario-names <names>" help="scenarios 类型下只运行指定场景（逗号分隔）"
//USAGE flag "--preserve" help="默认保留测试容器和镜像"
//USAGE flag "--plain" help="默认启用 BUILDKIT_PROGRESS=plain"
//USAGE flag "-y --yes" help="默认选中确认执行，并自动保存日志"
/**
 * DevContainer Features 测试任务
 *
 * test.ts 保留测试任务自身的参数解析、命令构造与执行流程；
 * utils.ts 只保留 test / cleanup 共用的运行时配置。
 */

import type { WorkflowCommandTaskIO } from 'clack-kit'
import { defineStep, defineSteps, defineWorkflow } from 'clack-kit'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import {
  ROOT,
  createTaskLogConfig,
  createTaskRunOptions,
  createTaskWorkflowKit,
  isNonInteractiveRun,
} from './utils'

const TEST_TYPES = ['autogenerated', 'global', 'scenarios'] as const
const RETAINED_TEST_ARTIFACT_PATTERN = 'vsc-.*-features(-uid)?'
const FALLBACK_AUTOGENERATED_BASE_IMAGES = [
  'debian:latest',
  'ubuntu:latest',
  'mcr.microsoft.com/devcontainers/base:ubuntu',
] as const
const DEFAULT_FEATURE = 'common'
const DEFAULT_FEATURE_OPTIONS = [{ value: DEFAULT_FEATURE, label: DEFAULT_FEATURE }]

type TestType = (typeof TEST_TYPES)[number]
type FeatureOption = (typeof DEFAULT_FEATURE_OPTIONS)[number]
type UsageArgs = {
  testType?: TestType
  feature?: string
  workflowMatrixBaseImages?: string[]
  scenarioNames?: string[]
  preserveContainers: boolean
  plainMode: boolean
  yes: boolean
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function shellQuote(value: string): string {
  return JSON.stringify(value)
}

function parseTestType(value: unknown): TestType | undefined {
  return typeof value === 'string' ? TEST_TYPES.find(testType => testType === value) : undefined
}

function parseUsageList(value: string | undefined): string[] | undefined {
  const values = value
    ?.split(',')
    .map(item => item.trim())
    .filter(Boolean)

  return values?.length ? [...new Set(values)] : undefined
}

function getFeatures(root: string = ROOT): FeatureOption[] {
  const srcDir = join(root, 'src')
  if (!existsSync(srcDir)) {
    return DEFAULT_FEATURE_OPTIONS
  }

  const features = readdirSync(srcDir, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory() && existsSync(join(srcDir, dirent.name, 'devcontainer-feature.json')))
    .map(({ name }) => ({ value: name, label: name }))

  return features.length ? features : DEFAULT_FEATURE_OPTIONS
}

function getScenarioNames(feature: string, root: string = ROOT): string[] {
  const scenariosPath = join(root, 'test', feature, 'scenarios.json')
  if (!existsSync(scenariosPath)) {
    return []
  }

  const parsed = JSON.parse(readFileSync(scenariosPath, 'utf-8'))
  if (!isRecord(parsed)) {
    throw new Error(`${scenariosPath} 必须是对象形式的场景映射`)
  }

  return Object.keys(parsed)
}

function getWorkflowAutogeneratedBaseImages(root: string = ROOT): string[] {
  const workflowFile = join(root, '.github', 'workflows', 'test.yaml')
  if (!existsSync(workflowFile)) {
    return [...FALLBACK_AUTOGENERATED_BASE_IMAGES]
  }

  const match = readFileSync(workflowFile, 'utf-8').match(/baseImage:\s*\n((?:\s*-\s+.+\n?)+)/m)
  if (!match) {
    return [...FALLBACK_AUTOGENERATED_BASE_IMAGES]
  }

  const images = match[1]
    .split(/\r?\n/)
    .map(line => line.trim())
    .filter(Boolean)
    .map(line => line.replace(/^- /, '').trim().replace(/^['"]|['"]$/g, ''))

  return images.length ? images : [...FALLBACK_AUTOGENERATED_BASE_IMAGES]
}

function getDefaultFeatureValue(features: FeatureOption[]): string {
  return features[0]?.value ?? DEFAULT_FEATURE
}

function normalizeStringArray(values: unknown): string[] {
  if (!Array.isArray(values)) {
    return []
  }

  return [...new Set(
    values
      .map(value => typeof value === 'string' ? value.trim() : '')
      .filter(Boolean),
  )]
}

function resolveSelectedItems(
  values: unknown,
  availableItems: string[],
  itemLabel: string,
  sourceLabel: string,
): string[] | undefined {
  const selectedItems = normalizeStringArray(values)
  if (selectedItems.length === 0) {
    return undefined
  }

  const availableSet = new Set(availableItems)
  const invalidItems = selectedItems.filter(item => !availableSet.has(item))
  if (invalidItems.length > 0) {
    throw new Error(`未找到${sourceLabel}中的${itemLabel}：${invalidItems.join(', ')}`)
  }

  return availableItems.filter(item => selectedItems.includes(item))
}

function resolveTestType(values: Record<string, unknown>): TestType {
  return parseTestType(values.testType) ?? 'scenarios'
}

function resolveFeature(values: Record<string, unknown>, features: FeatureOption[]): string {
  return typeof values.feature === 'string' && values.feature.trim()
    ? values.feature.trim()
    : getDefaultFeatureValue(features)
}

function buildInitialValues(args: UsageArgs, isNonInteractive: boolean): Record<string, unknown> {
  return {
    ...(args.testType ? { testType: args.testType } : {}),
    ...(args.feature ? { feature: args.feature } : {}),
    ...(args.workflowMatrixBaseImages?.length
      ? { workflowMatrixBaseImages: args.workflowMatrixBaseImages }
      : isNonInteractive && args.testType === 'autogenerated'
        ? { workflowMatrixBaseImages: [] }
        : {}),
    ...(args.scenarioNames?.length
      ? { scenarioNames: args.scenarioNames }
      : isNonInteractive && args.testType === 'scenarios'
        ? { scenarioNames: [] }
        : {}),
    ...(args.preserveContainers ? { preserveContainers: true } : {}),
    ...(args.plainMode ? { plainMode: true } : {}),
  }
}

function buildSingleTestCommand(
  options: {
    testType: TestType
    feature?: string
    baseImage?: string
    scenarioFilter?: string
    preserveContainers: boolean
    plainMode: boolean
  },
  features: FeatureOption[],
): string {
  const parts: string[] = []

  if (options.plainMode) {
    parts.push('BUILDKIT_PROGRESS=plain')
  }

  parts.push('devcontainer', 'features', 'test')

  switch (options.testType) {
    case 'autogenerated':
      parts.push('--skip-scenarios', '-f', shellQuote(options.feature ?? getDefaultFeatureValue(features)))
      if (options.baseImage) {
        parts.push('-i', shellQuote(options.baseImage))
      }
      break
    case 'global':
      parts.push('--global-scenarios-only')
      break
    case 'scenarios':
      parts.push(
        '-f',
        shellQuote(options.feature ?? getDefaultFeatureValue(features)),
        '--skip-autogenerated',
        '--skip-duplicated',
      )
      if (options.scenarioFilter) {
        parts.push('--filter', shellQuote(options.scenarioFilter))
      }
      break
  }

  if (options.preserveContainers) {
    parts.push('--preserve-test-containers')
  }

  parts.push(shellQuote(ROOT))
  return parts.join(' ')
}

function buildTestExecutionCommand(
  values: Record<string, unknown>,
  context: {
    features: FeatureOption[]
    workflowAutogeneratedBaseImages: string[]
  },
): string[] {
  const testType = resolveTestType(values)
  const preserveContainers = values.preserveContainers === true
  const plainMode = values.plainMode === true

  if (testType === 'global') {
    return [buildSingleTestCommand({ testType, preserveContainers, plainMode }, context.features)]
  }

  const feature = resolveFeature(values, context.features)

  if (testType === 'autogenerated') {
    const baseImages = resolveSelectedItems(
      values.workflowMatrixBaseImages,
      context.workflowAutogeneratedBaseImages,
      '基础镜像',
      '.github/workflows/test.yaml 的 workflow 矩阵',
    ) ?? context.workflowAutogeneratedBaseImages

    return baseImages.map(baseImage =>
      buildSingleTestCommand(
        {
          testType,
          feature,
          baseImage,
          preserveContainers,
          plainMode,
        },
        context.features,
      ),
    )
  }

  const scenarioNames = getScenarioNames(feature)
  const selectedScenarioNames = resolveSelectedItems(
    values.scenarioNames,
    scenarioNames,
    '场景',
    `test/${feature}/scenarios.json`,
  )

  if (selectedScenarioNames && selectedScenarioNames.length < scenarioNames.length) {
    return selectedScenarioNames.map(scenarioName =>
      buildSingleTestCommand(
        {
          testType,
          feature,
          scenarioFilter: scenarioName,
          preserveContainers,
          plainMode,
        },
        context.features,
      ),
    )
  }

  return [buildSingleTestCommand({ testType, feature, preserveContainers, plainMode }, context.features)]
}

async function showRetainedTestContainers(io: WorkflowCommandTaskIO): Promise<void> {
  io.log('info', '保留的测试容器：')
  await io.exec(
    `docker ps -a --format "table {{.ID}}\\t{{.Names}}\\t{{.Image}}\\t{{.Status}}" 2>/dev/null | grep -E "CONTAINER ID|${RETAINED_TEST_ARTIFACT_PATTERN}" || echo "（无容器）"`,
  )
  io.log('info', '提示：运行 `mise run cleanup` 或 `npm run test:cleanup` 可清理这些容器')
}

const usageArgs: UsageArgs = {
  testType: parseTestType(process.env.usage_test_type ?? process.env.usage_mode),
  feature: process.env.usage_feature,
  workflowMatrixBaseImages: parseUsageList(process.env.usage_workflow_matrix_images),
  scenarioNames: parseUsageList(process.env.usage_scenario_names),
  preserveContainers: process.env.usage_preserve === 'true',
  plainMode: process.env.usage_plain === 'true',
  yes: process.env.usage_yes === 'true',
}

const isNonInteractive = isNonInteractiveRun(usageArgs.yes)
const features = getFeatures()
const workflowAutogeneratedBaseImages = getWorkflowAutogeneratedBaseImages()

const workflow = defineWorkflow({
  id: 'devcontainer-feature-test',
  intro: '🧪 DevContainer Features 测试工具',
  log: createTaskLogConfig(isNonInteractive),
  snapshot: {
    label({ values, colors }) {
      const commands = buildTestExecutionCommand(values, { features, workflowAutogeneratedBaseImages })
      return `\n${colors.gray(commands.join('\n'))}`
    },
  },
  steps: defineSteps([
    defineStep.select({
      id: 'testType',
      message: '选择测试类型',
      defaultValue: 'scenarios',
      options: [
        { value: 'autogenerated', label: 'autogenerated', hint: '自动生成测试；固定使用 workflow 基础镜像矩阵，可多选子集' },
        { value: 'global', label: 'global', hint: '运行 test/_global 下的全局场景' },
        { value: 'scenarios', label: 'scenarios', hint: '运行 feature 自带的 scenarios.json 场景（推荐）' },
      ],
    }),

    defineStep.select({
      id: 'feature',
      message: '选择要测试的 Feature',
      when: ({ values }) => resolveTestType(values) !== 'global',
      options: features,
    }),

    defineStep.multiselect({
      id: 'workflowMatrixBaseImages',
      message: '选择要运行的基础镜像',
      defaultValue: [...workflowAutogeneratedBaseImages],
      when: ({ values }) => resolveTestType(values) === 'autogenerated',
      options: workflowAutogeneratedBaseImages,
    }),

    defineStep.autocompleteMultiselect({
      id: 'scenarioNames',
      message: '选择要运行的 scenarios',
      placeholder: '输入关键词筛选场景名',
      required: true,
      defaultValue: ({ values }) => getScenarioNames(resolveFeature(values, features)).slice(0, 1),
      when: ({ values }) => resolveTestType(values) === 'scenarios',
      options: ({ values }) => getScenarioNames(resolveFeature(values, features)),
    }),

    defineStep.confirm({
      id: 'preserveContainers',
      message: '保留测试容器和镜像？（用于调试）',
      defaultValue: false,
    }),

    defineStep.confirm({
      id: 'plainMode',
      message: '使用 plain 模式显示构建输出？（详细日志）',
      defaultValue: false,
    }),

    defineStep.command({
      title: 'Run',
      tty: 'passthrough',
      confirm: { message: '确认执行测试命令？', defaultValue: true },
      exitProcessOnFailure: true,
      command: ({ values }) => buildTestExecutionCommand(values, { features, workflowAutogeneratedBaseImages }),
    }),

    defineStep.command({
      title: '查看保留的测试容器',
      confirm: { message: '确认查看保留的测试容器？', defaultValue: true },
      tty: 'passthrough',
      when: ({ values }) => values.preserveContainers === true,
      run: (_ctx, io) => showRetainedTestContainers(io),
    }),
  ]),
})

try {
  await createTaskWorkflowKit().runSafely(workflow, createTaskRunOptions({
    entry: 'mise-tasks/test.ts',
    initialValues: buildInitialValues(usageArgs, isNonInteractive),
    isNonInteractive,
  }))
} catch {
  process.exit(1)
}
